
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.colored.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.colored.item.YellowSwordItem;
import net.mcreator.colored.item.YellowShovelItem;
import net.mcreator.colored.item.YellowPickaxeItem;
import net.mcreator.colored.item.YellowItem;
import net.mcreator.colored.item.YellowHoeItem;
import net.mcreator.colored.item.YellowAxeItem;
import net.mcreator.colored.item.YellowArmorItem;
import net.mcreator.colored.item.WhiteSwordItem;
import net.mcreator.colored.item.WhiteShovelItem;
import net.mcreator.colored.item.WhitePickaxeItem;
import net.mcreator.colored.item.WhiteItem;
import net.mcreator.colored.item.WhiteHoeItem;
import net.mcreator.colored.item.WhiteAxeItem;
import net.mcreator.colored.item.WhiteArmorItem;
import net.mcreator.colored.item.RedSwordItem;
import net.mcreator.colored.item.RedShovelItem;
import net.mcreator.colored.item.RedPickaxeItem;
import net.mcreator.colored.item.RedItem;
import net.mcreator.colored.item.RedHoeItem;
import net.mcreator.colored.item.RedAxeItem;
import net.mcreator.colored.item.RedArmorItem;
import net.mcreator.colored.item.Pink1SwordItem;
import net.mcreator.colored.item.Pink1ShovelItem;
import net.mcreator.colored.item.Pink1PickaxeItem;
import net.mcreator.colored.item.Pink1Item;
import net.mcreator.colored.item.Pink1HoeItem;
import net.mcreator.colored.item.Pink1AxeItem;
import net.mcreator.colored.item.Pink1ArmorItem;
import net.mcreator.colored.item.GreenSwordItem;
import net.mcreator.colored.item.GreenShovelItem;
import net.mcreator.colored.item.GreenPickaxeItem;
import net.mcreator.colored.item.GreenItem;
import net.mcreator.colored.item.GreenHoeItem;
import net.mcreator.colored.item.GreenAxeItem;
import net.mcreator.colored.item.GreenArmorItem;
import net.mcreator.colored.item.CyanSwordItem;
import net.mcreator.colored.item.CyanShovelItem;
import net.mcreator.colored.item.CyanPickaxeItem;
import net.mcreator.colored.item.CyanItem;
import net.mcreator.colored.item.CyanHoeItem;
import net.mcreator.colored.item.CyanAxeItem;
import net.mcreator.colored.item.CyanArmorItem;
import net.mcreator.colored.item.BlackSwordItem;
import net.mcreator.colored.item.BlackShovelItem;
import net.mcreator.colored.item.BlackPickaxeItem;
import net.mcreator.colored.item.BlackItem;
import net.mcreator.colored.item.BlackHoeItem;
import net.mcreator.colored.item.BlackAxeItem;
import net.mcreator.colored.item.BlackArmorItem;
import net.mcreator.colored.ColoredMod;

public class ColoredModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ColoredMod.MODID);
	public static final RegistryObject<Item> GREEN = REGISTRY.register("green", () -> new GreenItem());
	public static final RegistryObject<Item> GREEN_ORE = block(ColoredModBlocks.GREEN_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_BLOCK = block(ColoredModBlocks.GREEN_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_PICKAXE = REGISTRY.register("green_pickaxe", () -> new GreenPickaxeItem());
	public static final RegistryObject<Item> GREEN_AXE = REGISTRY.register("green_axe", () -> new GreenAxeItem());
	public static final RegistryObject<Item> GREEN_SWORD = REGISTRY.register("green_sword", () -> new GreenSwordItem());
	public static final RegistryObject<Item> GREEN_SHOVEL = REGISTRY.register("green_shovel", () -> new GreenShovelItem());
	public static final RegistryObject<Item> GREEN_HOE = REGISTRY.register("green_hoe", () -> new GreenHoeItem());
	public static final RegistryObject<Item> GREEN_ARMOR_HELMET = REGISTRY.register("green_armor_helmet", () -> new GreenArmorItem.Helmet());
	public static final RegistryObject<Item> GREEN_ARMOR_CHESTPLATE = REGISTRY.register("green_armor_chestplate",
			() -> new GreenArmorItem.Chestplate());
	public static final RegistryObject<Item> GREEN_ARMOR_LEGGINGS = REGISTRY.register("green_armor_leggings", () -> new GreenArmorItem.Leggings());
	public static final RegistryObject<Item> GREEN_ARMOR_BOOTS = REGISTRY.register("green_armor_boots", () -> new GreenArmorItem.Boots());
	public static final RegistryObject<Item> GREEN_1_WOOD = block(ColoredModBlocks.GREEN_1_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_1_LOG = block(ColoredModBlocks.GREEN_1_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_1_PLANKS = block(ColoredModBlocks.GREEN_1_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_1_LEAVES = block(ColoredModBlocks.GREEN_1_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GREEN_1_STAIRS = block(ColoredModBlocks.GREEN_1_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_1_SLAB = block(ColoredModBlocks.GREEN_1_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> GREEN_1_FENCE = block(ColoredModBlocks.GREEN_1_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> GREEN_1_FENCE_GATE = block(ColoredModBlocks.GREEN_1_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> GREEN_1_PRESSURE_PLATE = block(ColoredModBlocks.GREEN_1_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> GREEN_1_BUTTON = block(ColoredModBlocks.GREEN_1_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED = REGISTRY.register("red", () -> new RedItem());
	public static final RegistryObject<Item> RED_ORE = block(ColoredModBlocks.RED_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_BLOCK = block(ColoredModBlocks.RED_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_PICKAXE = REGISTRY.register("red_pickaxe", () -> new RedPickaxeItem());
	public static final RegistryObject<Item> RED_AXE = REGISTRY.register("red_axe", () -> new RedAxeItem());
	public static final RegistryObject<Item> RED_SWORD = REGISTRY.register("red_sword", () -> new RedSwordItem());
	public static final RegistryObject<Item> RED_SHOVEL = REGISTRY.register("red_shovel", () -> new RedShovelItem());
	public static final RegistryObject<Item> RED_HOE = REGISTRY.register("red_hoe", () -> new RedHoeItem());
	public static final RegistryObject<Item> RED_ARMOR_HELMET = REGISTRY.register("red_armor_helmet", () -> new RedArmorItem.Helmet());
	public static final RegistryObject<Item> RED_ARMOR_CHESTPLATE = REGISTRY.register("red_armor_chestplate", () -> new RedArmorItem.Chestplate());
	public static final RegistryObject<Item> RED_ARMOR_LEGGINGS = REGISTRY.register("red_armor_leggings", () -> new RedArmorItem.Leggings());
	public static final RegistryObject<Item> RED_ARMOR_BOOTS = REGISTRY.register("red_armor_boots", () -> new RedArmorItem.Boots());
	public static final RegistryObject<Item> RED_1_WOOD = block(ColoredModBlocks.RED_1_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_1_LOG = block(ColoredModBlocks.RED_1_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_1_PLANKS = block(ColoredModBlocks.RED_1_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_1_LEAVES = block(ColoredModBlocks.RED_1_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> RED_1_STAIRS = block(ColoredModBlocks.RED_1_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_1_SLAB = block(ColoredModBlocks.RED_1_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> RED_1_FENCE = block(ColoredModBlocks.RED_1_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> RED_1_FENCE_GATE = block(ColoredModBlocks.RED_1_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> RED_1_PRESSURE_PLATE = block(ColoredModBlocks.RED_1_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> RED_1_BUTTON = block(ColoredModBlocks.RED_1_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN = REGISTRY.register("cyan", () -> new CyanItem());
	public static final RegistryObject<Item> CYAN_ORE = block(ColoredModBlocks.CYAN_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_BLOCK = block(ColoredModBlocks.CYAN_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_PICKAXE = REGISTRY.register("cyan_pickaxe", () -> new CyanPickaxeItem());
	public static final RegistryObject<Item> CYAN_AXE = REGISTRY.register("cyan_axe", () -> new CyanAxeItem());
	public static final RegistryObject<Item> CYAN_SWORD = REGISTRY.register("cyan_sword", () -> new CyanSwordItem());
	public static final RegistryObject<Item> CYAN_SHOVEL = REGISTRY.register("cyan_shovel", () -> new CyanShovelItem());
	public static final RegistryObject<Item> CYAN_HOE = REGISTRY.register("cyan_hoe", () -> new CyanHoeItem());
	public static final RegistryObject<Item> CYAN_ARMOR_HELMET = REGISTRY.register("cyan_armor_helmet", () -> new CyanArmorItem.Helmet());
	public static final RegistryObject<Item> CYAN_ARMOR_CHESTPLATE = REGISTRY.register("cyan_armor_chestplate", () -> new CyanArmorItem.Chestplate());
	public static final RegistryObject<Item> CYAN_ARMOR_LEGGINGS = REGISTRY.register("cyan_armor_leggings", () -> new CyanArmorItem.Leggings());
	public static final RegistryObject<Item> CYAN_ARMOR_BOOTS = REGISTRY.register("cyan_armor_boots", () -> new CyanArmorItem.Boots());
	public static final RegistryObject<Item> CYAN_1_WOOD = block(ColoredModBlocks.CYAN_1_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_1_LOG = block(ColoredModBlocks.CYAN_1_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_1_PLANKS = block(ColoredModBlocks.CYAN_1_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_1_LEAVES = block(ColoredModBlocks.CYAN_1_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CYAN_1_STAIRS = block(ColoredModBlocks.CYAN_1_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_1_SLAB = block(ColoredModBlocks.CYAN_1_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> CYAN_1_FENCE = block(ColoredModBlocks.CYAN_1_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> CYAN_1_FENCE_GATE = block(ColoredModBlocks.CYAN_1_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CYAN_1_PRESSURE_PLATE = block(ColoredModBlocks.CYAN_1_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> CYAN_1_BUTTON = block(ColoredModBlocks.CYAN_1_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW = REGISTRY.register("yellow", () -> new YellowItem());
	public static final RegistryObject<Item> YELLOW_ORE = block(ColoredModBlocks.YELLOW_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_BLOCK = block(ColoredModBlocks.YELLOW_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_PICKAXE = REGISTRY.register("yellow_pickaxe", () -> new YellowPickaxeItem());
	public static final RegistryObject<Item> YELLOW_AXE = REGISTRY.register("yellow_axe", () -> new YellowAxeItem());
	public static final RegistryObject<Item> YELLOW_SWORD = REGISTRY.register("yellow_sword", () -> new YellowSwordItem());
	public static final RegistryObject<Item> YELLOW_SHOVEL = REGISTRY.register("yellow_shovel", () -> new YellowShovelItem());
	public static final RegistryObject<Item> YELLOW_HOE = REGISTRY.register("yellow_hoe", () -> new YellowHoeItem());
	public static final RegistryObject<Item> YELLOW_ARMOR_HELMET = REGISTRY.register("yellow_armor_helmet", () -> new YellowArmorItem.Helmet());
	public static final RegistryObject<Item> YELLOW_ARMOR_CHESTPLATE = REGISTRY.register("yellow_armor_chestplate",
			() -> new YellowArmorItem.Chestplate());
	public static final RegistryObject<Item> YELLOW_ARMOR_LEGGINGS = REGISTRY.register("yellow_armor_leggings", () -> new YellowArmorItem.Leggings());
	public static final RegistryObject<Item> YELLOW_ARMOR_BOOTS = REGISTRY.register("yellow_armor_boots", () -> new YellowArmorItem.Boots());
	public static final RegistryObject<Item> YELLOW_1_WOOD = block(ColoredModBlocks.YELLOW_1_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_1_LOG = block(ColoredModBlocks.YELLOW_1_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_1_PLANKS = block(ColoredModBlocks.YELLOW_1_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_1_LEAVES = block(ColoredModBlocks.YELLOW_1_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> YELLOW_1_STAIRS = block(ColoredModBlocks.YELLOW_1_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_1_SLAB = block(ColoredModBlocks.YELLOW_1_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> YELLOW_1_FENCE = block(ColoredModBlocks.YELLOW_1_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> YELLOW_1_FENCE_GATE = block(ColoredModBlocks.YELLOW_1_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> YELLOW_1_PRESSURE_PLATE = block(ColoredModBlocks.YELLOW_1_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> YELLOW_1_BUTTON = block(ColoredModBlocks.YELLOW_1_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_WOOD = block(ColoredModBlocks.PINK_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_LOG = block(ColoredModBlocks.PINK_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_PLANKS = block(ColoredModBlocks.PINK_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_LEAVES = block(ColoredModBlocks.PINK_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PINK_STAIRS = block(ColoredModBlocks.PINK_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_SLAB = block(ColoredModBlocks.PINK_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_FENCE = block(ColoredModBlocks.PINK_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PINK_FENCE_GATE = block(ColoredModBlocks.PINK_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PINK_PRESSURE_PLATE = block(ColoredModBlocks.PINK_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PINK_BUTTON = block(ColoredModBlocks.PINK_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_1 = REGISTRY.register("pink_1", () -> new Pink1Item());
	public static final RegistryObject<Item> PINK_1_ORE = block(ColoredModBlocks.PINK_1_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_1_BLOCK = block(ColoredModBlocks.PINK_1_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> PINK_1_PICKAXE = REGISTRY.register("pink_1_pickaxe", () -> new Pink1PickaxeItem());
	public static final RegistryObject<Item> PINK_1_AXE = REGISTRY.register("pink_1_axe", () -> new Pink1AxeItem());
	public static final RegistryObject<Item> PINK_1_SWORD = REGISTRY.register("pink_1_sword", () -> new Pink1SwordItem());
	public static final RegistryObject<Item> PINK_1_SHOVEL = REGISTRY.register("pink_1_shovel", () -> new Pink1ShovelItem());
	public static final RegistryObject<Item> PINK_1_HOE = REGISTRY.register("pink_1_hoe", () -> new Pink1HoeItem());
	public static final RegistryObject<Item> PINK_1_ARMOR_HELMET = REGISTRY.register("pink_1_armor_helmet", () -> new Pink1ArmorItem.Helmet());
	public static final RegistryObject<Item> PINK_1_ARMOR_CHESTPLATE = REGISTRY.register("pink_1_armor_chestplate",
			() -> new Pink1ArmorItem.Chestplate());
	public static final RegistryObject<Item> PINK_1_ARMOR_LEGGINGS = REGISTRY.register("pink_1_armor_leggings", () -> new Pink1ArmorItem.Leggings());
	public static final RegistryObject<Item> PINK_1_ARMOR_BOOTS = REGISTRY.register("pink_1_armor_boots", () -> new Pink1ArmorItem.Boots());
	public static final RegistryObject<Item> WHITE = REGISTRY.register("white", () -> new WhiteItem());
	public static final RegistryObject<Item> WHITE_ORE = block(ColoredModBlocks.WHITE_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_BLOCK = block(ColoredModBlocks.WHITE_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_PICKAXE = REGISTRY.register("white_pickaxe", () -> new WhitePickaxeItem());
	public static final RegistryObject<Item> WHITE_AXE = REGISTRY.register("white_axe", () -> new WhiteAxeItem());
	public static final RegistryObject<Item> WHITE_SWORD = REGISTRY.register("white_sword", () -> new WhiteSwordItem());
	public static final RegistryObject<Item> WHITE_SHOVEL = REGISTRY.register("white_shovel", () -> new WhiteShovelItem());
	public static final RegistryObject<Item> WHITE_HOE = REGISTRY.register("white_hoe", () -> new WhiteHoeItem());
	public static final RegistryObject<Item> WHITE_ARMOR_HELMET = REGISTRY.register("white_armor_helmet", () -> new WhiteArmorItem.Helmet());
	public static final RegistryObject<Item> WHITE_ARMOR_CHESTPLATE = REGISTRY.register("white_armor_chestplate",
			() -> new WhiteArmorItem.Chestplate());
	public static final RegistryObject<Item> WHITE_ARMOR_LEGGINGS = REGISTRY.register("white_armor_leggings", () -> new WhiteArmorItem.Leggings());
	public static final RegistryObject<Item> WHITE_ARMOR_BOOTS = REGISTRY.register("white_armor_boots", () -> new WhiteArmorItem.Boots());
	public static final RegistryObject<Item> WHITE_1_WOOD = block(ColoredModBlocks.WHITE_1_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_1_LOG = block(ColoredModBlocks.WHITE_1_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_1_PLANKS = block(ColoredModBlocks.WHITE_1_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_1_LEAVES = block(ColoredModBlocks.WHITE_1_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WHITE_1_STAIRS = block(ColoredModBlocks.WHITE_1_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_1_SLAB = block(ColoredModBlocks.WHITE_1_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> WHITE_1_FENCE = block(ColoredModBlocks.WHITE_1_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> WHITE_1_FENCE_GATE = block(ColoredModBlocks.WHITE_1_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WHITE_1_PRESSURE_PLATE = block(ColoredModBlocks.WHITE_1_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> WHITE_1_BUTTON = block(ColoredModBlocks.WHITE_1_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK = REGISTRY.register("black", () -> new BlackItem());
	public static final RegistryObject<Item> BLACK_ORE = block(ColoredModBlocks.BLACK_ORE, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_BLOCK = block(ColoredModBlocks.BLACK_BLOCK, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_PICKAXE = REGISTRY.register("black_pickaxe", () -> new BlackPickaxeItem());
	public static final RegistryObject<Item> BLACK_AXE = REGISTRY.register("black_axe", () -> new BlackAxeItem());
	public static final RegistryObject<Item> BLACK_SWORD = REGISTRY.register("black_sword", () -> new BlackSwordItem());
	public static final RegistryObject<Item> BLACK_SHOVEL = REGISTRY.register("black_shovel", () -> new BlackShovelItem());
	public static final RegistryObject<Item> BLACK_HOE = REGISTRY.register("black_hoe", () -> new BlackHoeItem());
	public static final RegistryObject<Item> BLACK_ARMOR_HELMET = REGISTRY.register("black_armor_helmet", () -> new BlackArmorItem.Helmet());
	public static final RegistryObject<Item> BLACK_ARMOR_CHESTPLATE = REGISTRY.register("black_armor_chestplate",
			() -> new BlackArmorItem.Chestplate());
	public static final RegistryObject<Item> BLACK_ARMOR_LEGGINGS = REGISTRY.register("black_armor_leggings", () -> new BlackArmorItem.Leggings());
	public static final RegistryObject<Item> BLACK_ARMOR_BOOTS = REGISTRY.register("black_armor_boots", () -> new BlackArmorItem.Boots());
	public static final RegistryObject<Item> BLACK_1_WOOD = block(ColoredModBlocks.BLACK_1_WOOD, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_1_LOG = block(ColoredModBlocks.BLACK_1_LOG, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_1_PLANKS = block(ColoredModBlocks.BLACK_1_PLANKS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_1_LEAVES = block(ColoredModBlocks.BLACK_1_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLACK_1_STAIRS = block(ColoredModBlocks.BLACK_1_STAIRS, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_1_SLAB = block(ColoredModBlocks.BLACK_1_SLAB, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> BLACK_1_FENCE = block(ColoredModBlocks.BLACK_1_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> BLACK_1_FENCE_GATE = block(ColoredModBlocks.BLACK_1_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BLACK_1_PRESSURE_PLATE = block(ColoredModBlocks.BLACK_1_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> BLACK_1_BUTTON = block(ColoredModBlocks.BLACK_1_BUTTON, CreativeModeTab.TAB_BUILDING_BLOCKS);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
