
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.colored.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.colored.block.YellowOreBlock;
import net.mcreator.colored.block.YellowBlockBlock;
import net.mcreator.colored.block.Yellow1WoodBlock;
import net.mcreator.colored.block.Yellow1StairsBlock;
import net.mcreator.colored.block.Yellow1SlabBlock;
import net.mcreator.colored.block.Yellow1PressurePlateBlock;
import net.mcreator.colored.block.Yellow1PlanksBlock;
import net.mcreator.colored.block.Yellow1LogBlock;
import net.mcreator.colored.block.Yellow1LeavesBlock;
import net.mcreator.colored.block.Yellow1FenceGateBlock;
import net.mcreator.colored.block.Yellow1FenceBlock;
import net.mcreator.colored.block.Yellow1ButtonBlock;
import net.mcreator.colored.block.WhiteOreBlock;
import net.mcreator.colored.block.WhiteBlockBlock;
import net.mcreator.colored.block.White1WoodBlock;
import net.mcreator.colored.block.White1StairsBlock;
import net.mcreator.colored.block.White1SlabBlock;
import net.mcreator.colored.block.White1PressurePlateBlock;
import net.mcreator.colored.block.White1PlanksBlock;
import net.mcreator.colored.block.White1LogBlock;
import net.mcreator.colored.block.White1LeavesBlock;
import net.mcreator.colored.block.White1FenceGateBlock;
import net.mcreator.colored.block.White1FenceBlock;
import net.mcreator.colored.block.White1ButtonBlock;
import net.mcreator.colored.block.RedOreBlock;
import net.mcreator.colored.block.RedBlockBlock;
import net.mcreator.colored.block.Red1WoodBlock;
import net.mcreator.colored.block.Red1StairsBlock;
import net.mcreator.colored.block.Red1SlabBlock;
import net.mcreator.colored.block.Red1PressurePlateBlock;
import net.mcreator.colored.block.Red1PlanksBlock;
import net.mcreator.colored.block.Red1LogBlock;
import net.mcreator.colored.block.Red1LeavesBlock;
import net.mcreator.colored.block.Red1FenceGateBlock;
import net.mcreator.colored.block.Red1FenceBlock;
import net.mcreator.colored.block.Red1ButtonBlock;
import net.mcreator.colored.block.PinkWoodBlock;
import net.mcreator.colored.block.PinkStairsBlock;
import net.mcreator.colored.block.PinkSlabBlock;
import net.mcreator.colored.block.PinkPressurePlateBlock;
import net.mcreator.colored.block.PinkPlanksBlock;
import net.mcreator.colored.block.PinkLogBlock;
import net.mcreator.colored.block.PinkLeavesBlock;
import net.mcreator.colored.block.PinkFenceGateBlock;
import net.mcreator.colored.block.PinkFenceBlock;
import net.mcreator.colored.block.PinkButtonBlock;
import net.mcreator.colored.block.Pink1OreBlock;
import net.mcreator.colored.block.Pink1BlockBlock;
import net.mcreator.colored.block.GreenOreBlock;
import net.mcreator.colored.block.GreenBlockBlock;
import net.mcreator.colored.block.Green1WoodBlock;
import net.mcreator.colored.block.Green1StairsBlock;
import net.mcreator.colored.block.Green1SlabBlock;
import net.mcreator.colored.block.Green1PressurePlateBlock;
import net.mcreator.colored.block.Green1PlanksBlock;
import net.mcreator.colored.block.Green1LogBlock;
import net.mcreator.colored.block.Green1LeavesBlock;
import net.mcreator.colored.block.Green1FenceGateBlock;
import net.mcreator.colored.block.Green1FenceBlock;
import net.mcreator.colored.block.Green1ButtonBlock;
import net.mcreator.colored.block.CyanOreBlock;
import net.mcreator.colored.block.CyanBlockBlock;
import net.mcreator.colored.block.Cyan1WoodBlock;
import net.mcreator.colored.block.Cyan1StairsBlock;
import net.mcreator.colored.block.Cyan1SlabBlock;
import net.mcreator.colored.block.Cyan1PressurePlateBlock;
import net.mcreator.colored.block.Cyan1PlanksBlock;
import net.mcreator.colored.block.Cyan1LogBlock;
import net.mcreator.colored.block.Cyan1LeavesBlock;
import net.mcreator.colored.block.Cyan1FenceGateBlock;
import net.mcreator.colored.block.Cyan1FenceBlock;
import net.mcreator.colored.block.Cyan1ButtonBlock;
import net.mcreator.colored.block.BlackOreBlock;
import net.mcreator.colored.block.BlackBlockBlock;
import net.mcreator.colored.block.Black1WoodBlock;
import net.mcreator.colored.block.Black1StairsBlock;
import net.mcreator.colored.block.Black1SlabBlock;
import net.mcreator.colored.block.Black1PressurePlateBlock;
import net.mcreator.colored.block.Black1PlanksBlock;
import net.mcreator.colored.block.Black1LogBlock;
import net.mcreator.colored.block.Black1LeavesBlock;
import net.mcreator.colored.block.Black1FenceGateBlock;
import net.mcreator.colored.block.Black1FenceBlock;
import net.mcreator.colored.block.Black1ButtonBlock;
import net.mcreator.colored.ColoredMod;

public class ColoredModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ColoredMod.MODID);
	public static final RegistryObject<Block> GREEN_ORE = REGISTRY.register("green_ore", () -> new GreenOreBlock());
	public static final RegistryObject<Block> GREEN_BLOCK = REGISTRY.register("green_block", () -> new GreenBlockBlock());
	public static final RegistryObject<Block> GREEN_1_WOOD = REGISTRY.register("green_1_wood", () -> new Green1WoodBlock());
	public static final RegistryObject<Block> GREEN_1_LOG = REGISTRY.register("green_1_log", () -> new Green1LogBlock());
	public static final RegistryObject<Block> GREEN_1_PLANKS = REGISTRY.register("green_1_planks", () -> new Green1PlanksBlock());
	public static final RegistryObject<Block> GREEN_1_LEAVES = REGISTRY.register("green_1_leaves", () -> new Green1LeavesBlock());
	public static final RegistryObject<Block> GREEN_1_STAIRS = REGISTRY.register("green_1_stairs", () -> new Green1StairsBlock());
	public static final RegistryObject<Block> GREEN_1_SLAB = REGISTRY.register("green_1_slab", () -> new Green1SlabBlock());
	public static final RegistryObject<Block> GREEN_1_FENCE = REGISTRY.register("green_1_fence", () -> new Green1FenceBlock());
	public static final RegistryObject<Block> GREEN_1_FENCE_GATE = REGISTRY.register("green_1_fence_gate", () -> new Green1FenceGateBlock());
	public static final RegistryObject<Block> GREEN_1_PRESSURE_PLATE = REGISTRY.register("green_1_pressure_plate",
			() -> new Green1PressurePlateBlock());
	public static final RegistryObject<Block> GREEN_1_BUTTON = REGISTRY.register("green_1_button", () -> new Green1ButtonBlock());
	public static final RegistryObject<Block> RED_ORE = REGISTRY.register("red_ore", () -> new RedOreBlock());
	public static final RegistryObject<Block> RED_BLOCK = REGISTRY.register("red_block", () -> new RedBlockBlock());
	public static final RegistryObject<Block> RED_1_WOOD = REGISTRY.register("red_1_wood", () -> new Red1WoodBlock());
	public static final RegistryObject<Block> RED_1_LOG = REGISTRY.register("red_1_log", () -> new Red1LogBlock());
	public static final RegistryObject<Block> RED_1_PLANKS = REGISTRY.register("red_1_planks", () -> new Red1PlanksBlock());
	public static final RegistryObject<Block> RED_1_LEAVES = REGISTRY.register("red_1_leaves", () -> new Red1LeavesBlock());
	public static final RegistryObject<Block> RED_1_STAIRS = REGISTRY.register("red_1_stairs", () -> new Red1StairsBlock());
	public static final RegistryObject<Block> RED_1_SLAB = REGISTRY.register("red_1_slab", () -> new Red1SlabBlock());
	public static final RegistryObject<Block> RED_1_FENCE = REGISTRY.register("red_1_fence", () -> new Red1FenceBlock());
	public static final RegistryObject<Block> RED_1_FENCE_GATE = REGISTRY.register("red_1_fence_gate", () -> new Red1FenceGateBlock());
	public static final RegistryObject<Block> RED_1_PRESSURE_PLATE = REGISTRY.register("red_1_pressure_plate", () -> new Red1PressurePlateBlock());
	public static final RegistryObject<Block> RED_1_BUTTON = REGISTRY.register("red_1_button", () -> new Red1ButtonBlock());
	public static final RegistryObject<Block> CYAN_ORE = REGISTRY.register("cyan_ore", () -> new CyanOreBlock());
	public static final RegistryObject<Block> CYAN_BLOCK = REGISTRY.register("cyan_block", () -> new CyanBlockBlock());
	public static final RegistryObject<Block> CYAN_1_WOOD = REGISTRY.register("cyan_1_wood", () -> new Cyan1WoodBlock());
	public static final RegistryObject<Block> CYAN_1_LOG = REGISTRY.register("cyan_1_log", () -> new Cyan1LogBlock());
	public static final RegistryObject<Block> CYAN_1_PLANKS = REGISTRY.register("cyan_1_planks", () -> new Cyan1PlanksBlock());
	public static final RegistryObject<Block> CYAN_1_LEAVES = REGISTRY.register("cyan_1_leaves", () -> new Cyan1LeavesBlock());
	public static final RegistryObject<Block> CYAN_1_STAIRS = REGISTRY.register("cyan_1_stairs", () -> new Cyan1StairsBlock());
	public static final RegistryObject<Block> CYAN_1_SLAB = REGISTRY.register("cyan_1_slab", () -> new Cyan1SlabBlock());
	public static final RegistryObject<Block> CYAN_1_FENCE = REGISTRY.register("cyan_1_fence", () -> new Cyan1FenceBlock());
	public static final RegistryObject<Block> CYAN_1_FENCE_GATE = REGISTRY.register("cyan_1_fence_gate", () -> new Cyan1FenceGateBlock());
	public static final RegistryObject<Block> CYAN_1_PRESSURE_PLATE = REGISTRY.register("cyan_1_pressure_plate", () -> new Cyan1PressurePlateBlock());
	public static final RegistryObject<Block> CYAN_1_BUTTON = REGISTRY.register("cyan_1_button", () -> new Cyan1ButtonBlock());
	public static final RegistryObject<Block> YELLOW_ORE = REGISTRY.register("yellow_ore", () -> new YellowOreBlock());
	public static final RegistryObject<Block> YELLOW_BLOCK = REGISTRY.register("yellow_block", () -> new YellowBlockBlock());
	public static final RegistryObject<Block> YELLOW_1_WOOD = REGISTRY.register("yellow_1_wood", () -> new Yellow1WoodBlock());
	public static final RegistryObject<Block> YELLOW_1_LOG = REGISTRY.register("yellow_1_log", () -> new Yellow1LogBlock());
	public static final RegistryObject<Block> YELLOW_1_PLANKS = REGISTRY.register("yellow_1_planks", () -> new Yellow1PlanksBlock());
	public static final RegistryObject<Block> YELLOW_1_LEAVES = REGISTRY.register("yellow_1_leaves", () -> new Yellow1LeavesBlock());
	public static final RegistryObject<Block> YELLOW_1_STAIRS = REGISTRY.register("yellow_1_stairs", () -> new Yellow1StairsBlock());
	public static final RegistryObject<Block> YELLOW_1_SLAB = REGISTRY.register("yellow_1_slab", () -> new Yellow1SlabBlock());
	public static final RegistryObject<Block> YELLOW_1_FENCE = REGISTRY.register("yellow_1_fence", () -> new Yellow1FenceBlock());
	public static final RegistryObject<Block> YELLOW_1_FENCE_GATE = REGISTRY.register("yellow_1_fence_gate", () -> new Yellow1FenceGateBlock());
	public static final RegistryObject<Block> YELLOW_1_PRESSURE_PLATE = REGISTRY.register("yellow_1_pressure_plate",
			() -> new Yellow1PressurePlateBlock());
	public static final RegistryObject<Block> YELLOW_1_BUTTON = REGISTRY.register("yellow_1_button", () -> new Yellow1ButtonBlock());
	public static final RegistryObject<Block> PINK_WOOD = REGISTRY.register("pink_wood", () -> new PinkWoodBlock());
	public static final RegistryObject<Block> PINK_LOG = REGISTRY.register("pink_log", () -> new PinkLogBlock());
	public static final RegistryObject<Block> PINK_PLANKS = REGISTRY.register("pink_planks", () -> new PinkPlanksBlock());
	public static final RegistryObject<Block> PINK_LEAVES = REGISTRY.register("pink_leaves", () -> new PinkLeavesBlock());
	public static final RegistryObject<Block> PINK_STAIRS = REGISTRY.register("pink_stairs", () -> new PinkStairsBlock());
	public static final RegistryObject<Block> PINK_SLAB = REGISTRY.register("pink_slab", () -> new PinkSlabBlock());
	public static final RegistryObject<Block> PINK_FENCE = REGISTRY.register("pink_fence", () -> new PinkFenceBlock());
	public static final RegistryObject<Block> PINK_FENCE_GATE = REGISTRY.register("pink_fence_gate", () -> new PinkFenceGateBlock());
	public static final RegistryObject<Block> PINK_PRESSURE_PLATE = REGISTRY.register("pink_pressure_plate", () -> new PinkPressurePlateBlock());
	public static final RegistryObject<Block> PINK_BUTTON = REGISTRY.register("pink_button", () -> new PinkButtonBlock());
	public static final RegistryObject<Block> PINK_1_ORE = REGISTRY.register("pink_1_ore", () -> new Pink1OreBlock());
	public static final RegistryObject<Block> PINK_1_BLOCK = REGISTRY.register("pink_1_block", () -> new Pink1BlockBlock());
	public static final RegistryObject<Block> WHITE_ORE = REGISTRY.register("white_ore", () -> new WhiteOreBlock());
	public static final RegistryObject<Block> WHITE_BLOCK = REGISTRY.register("white_block", () -> new WhiteBlockBlock());
	public static final RegistryObject<Block> WHITE_1_WOOD = REGISTRY.register("white_1_wood", () -> new White1WoodBlock());
	public static final RegistryObject<Block> WHITE_1_LOG = REGISTRY.register("white_1_log", () -> new White1LogBlock());
	public static final RegistryObject<Block> WHITE_1_PLANKS = REGISTRY.register("white_1_planks", () -> new White1PlanksBlock());
	public static final RegistryObject<Block> WHITE_1_LEAVES = REGISTRY.register("white_1_leaves", () -> new White1LeavesBlock());
	public static final RegistryObject<Block> WHITE_1_STAIRS = REGISTRY.register("white_1_stairs", () -> new White1StairsBlock());
	public static final RegistryObject<Block> WHITE_1_SLAB = REGISTRY.register("white_1_slab", () -> new White1SlabBlock());
	public static final RegistryObject<Block> WHITE_1_FENCE = REGISTRY.register("white_1_fence", () -> new White1FenceBlock());
	public static final RegistryObject<Block> WHITE_1_FENCE_GATE = REGISTRY.register("white_1_fence_gate", () -> new White1FenceGateBlock());
	public static final RegistryObject<Block> WHITE_1_PRESSURE_PLATE = REGISTRY.register("white_1_pressure_plate",
			() -> new White1PressurePlateBlock());
	public static final RegistryObject<Block> WHITE_1_BUTTON = REGISTRY.register("white_1_button", () -> new White1ButtonBlock());
	public static final RegistryObject<Block> BLACK_ORE = REGISTRY.register("black_ore", () -> new BlackOreBlock());
	public static final RegistryObject<Block> BLACK_BLOCK = REGISTRY.register("black_block", () -> new BlackBlockBlock());
	public static final RegistryObject<Block> BLACK_1_WOOD = REGISTRY.register("black_1_wood", () -> new Black1WoodBlock());
	public static final RegistryObject<Block> BLACK_1_LOG = REGISTRY.register("black_1_log", () -> new Black1LogBlock());
	public static final RegistryObject<Block> BLACK_1_PLANKS = REGISTRY.register("black_1_planks", () -> new Black1PlanksBlock());
	public static final RegistryObject<Block> BLACK_1_LEAVES = REGISTRY.register("black_1_leaves", () -> new Black1LeavesBlock());
	public static final RegistryObject<Block> BLACK_1_STAIRS = REGISTRY.register("black_1_stairs", () -> new Black1StairsBlock());
	public static final RegistryObject<Block> BLACK_1_SLAB = REGISTRY.register("black_1_slab", () -> new Black1SlabBlock());
	public static final RegistryObject<Block> BLACK_1_FENCE = REGISTRY.register("black_1_fence", () -> new Black1FenceBlock());
	public static final RegistryObject<Block> BLACK_1_FENCE_GATE = REGISTRY.register("black_1_fence_gate", () -> new Black1FenceGateBlock());
	public static final RegistryObject<Block> BLACK_1_PRESSURE_PLATE = REGISTRY.register("black_1_pressure_plate",
			() -> new Black1PressurePlateBlock());
	public static final RegistryObject<Block> BLACK_1_BUTTON = REGISTRY.register("black_1_button", () -> new Black1ButtonBlock());
}
